const Discord = require("discord.js");
const client = new Discord.Client();
const User = require("./models/User");
const mongoose = require("mongoose");
require("dotenv").config();
mongoose.Promise = global.Promise;

client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on("message", async msg => {
  let userData = {
    userId: msg.author.id,
    userName: msg.author.username,
    lastCheckin: new Date(),
    daysCompleted: 0,
    startDate: new Date(),
    roundsCompleted: 0,
    totalDaysCompleted: 0
  };
  const user = await User.findOne({ userId: msg.author.id });
  // shit ton of if statements, refactor at some point
  if (msg.content === "!join" && msg.channel.type === "dm" && !user) {
    User.create(userData);
    msg.author.send(
      "Nice! You have joined #100DaysOfCode! Check in everyday with !completed to make sure it is logged with the bot. To remove yourself from this event type !remove"
    );
  }
  if (msg.content === "!remove" && msg.channel.type === "dm" && user) {
    User.findOneAndDelete({ userId: msg.author.id }).exec();
    msg.author.send("No longer tracking your progress.");
  }
  if (msg.content === "!current" && msg.channel.type === "dm" && user) {
    msg.author.send(
      `You have completed [${user.daysCompleted}/100] days! Keep it up!`
    );
  }
  if (
    msg.content === "!completed" &&
    msg.channel.type === "dm" &&
    user &&
    user.lastCheckin.getTime() !== new Date(user.lastCheckin).getTime()
  ) {
    if (user.daysCompleted === 100) {
      User.findOneAndUpdate(
        { userId: msg.author.id },
        { $inc: { roundsCompleted: 1 }, $set: { daysCompleted: 0 } }
      ).exec();
      msg.author.send(
        "Woohoo! You completed a round of #100DaysOfCode! Your progress has been reset so feel free to start over when you want! :D"
      );
    } else {
      User.findOneAndUpdate(
        { userId: msg.author.id },
        { $inc: { daysCompleted: 1, totalDaysCompleted: 1 } }
      ).exec();
      msg.author.send("Day completed! Good job!");
    }
  } else if (
    msg.content === "!completed" &&
    msg.channel.type === "dm" &&
    user &&
    user.lastCheckin.getTime() === new Date(user.lastCheckin).getTime()
  ) {
    msg.author.send("You've already checked in!");
  }
  if (msg.content === "!stats" && user) {
    const embed = new Discord.RichEmbed()
      .setTitle(`#100DaysOfCode stats for ${user.userName}`)
      .setColor(0x00ae86)
      .setFooter(`Generated by: ${client.user.tag} on ${new Date()}`)
      .addField("Current days completed", user.daysCompleted)
      .addField("Rounds completed", user.roundsCompleted)
      .addField("Total days completed", user.totalDaysCompleted);
    msg.author.send({ embed });
  }
});

mongoose
  .connect("mongodb://localhost:27017/100daysofcode", { useNewUrlParser: true })
  .then(c => {
    console.log("Connected to DB.");
    client.login(process.env.BOT_TOKEN);
  })
  .catch(e => console.error(e));
